### ISSUE TITLE
Trouble building on OS X

### ISSUE THREAD

**Issue by google-feinberg** [martine/gocairo#2]
After some time spent downloading and building various prereqs (like cairo itself, and then fetching XQuartz and rebuilding cairo once I realized that gocairo uses the XLib bindings :), I run into this:

``` sh
$ CGO_CFLAGS="-I/opt/X11/include" go get -x github.com/martine/gocairo/cairo
WORK=/var/folders/00/0t8g8000h01000cxqpysvccm00391x/T/go-build834049204
mkdir -p $WORK/github.com/martine/gocairo/cairo/_obj/
mkdir -p $WORK/github.com/martine/gocairo/
cd /Users/feinberg/go/src/github.com/martine/gocairo/cairo
pkg-config --cflags cairo
pkg-config --libs cairo
CGO_LDFLAGS="-g" "-O2" "-L/usr/local/lib" "-lcairo" /usr/local/go/pkg/tool/darwin_amd64/cgo -objdir $WORK/github.com/martine/gocairo/cairo/_obj/ -- -I/usr/local/include/cairo -I/usr/local/include/pixman-1 -I/usr/local/include/freetype2 -I/usr/local/include/libpng16 -I $WORK/github.com/martine/gocairo/cairo/_obj/ -I/opt/X11/include cairo.go util.go
# github.com/martine/gocairo/cairo
could not determine kind of name for C.CAIRO_STATUS_JBIG2_GLOBAL_MISSING
could not determine kind of name for C.cairo_surface_get_device_scale
could not determine kind of name for C.cairo_surface_set_device_scale
```

**Comment by evmar** [comment]
We should make the xlib bits optional. I think there are build flags in go,
though I haven't used them. I'm not sure about the name thing. Might try
running "make" in a gocairo checkout to regenerate the binding then "git
diff" to see what changes in the generated code.

brevity due to phone

**Comment by google-feinberg** [comment]
This line in the Makefile

``` sh
sed -e 's/<X11\/Xlib\.h>/"fake-xlib.h"/' /usr/include/cairo/cairo-xlib.h
```

fails because it assumes that cairo is in `/usr/include`, but it's in `/usr/local/include` on my system.

The next line knows about where cairo is, though!

``` sh
$ pkg-config --cflags cairo cairo-xlib
-I/usr/local/include/cairo -I/usr/X11/include -I/usr/local/include/cairo -I/usr/local/include/pixman-1 -I/usr/local/include/freetype2 -I/usr/local/include/libpng16
```

**Comment by google-feinberg** [comment]
Update: actually, pkg-config is wrong about the location of X11. Weird.

**Comment by evmar** [comment]
You probably don't even want the x11 bits. That's just an experiment that
doesn't work yet.

brevity due to phone

**Comment by google-feinberg** [comment]
I believe the problem may be that I don't have `/usr/share/gtk-doc/html/cairo/cairo.devhelp2`.

**Comment by evmar** [comment]
Sorry, I've only ever run this on my own laptop.  I will add flags etc. for all of this.
You can comment out the code that loads that file, all you'll lose are the links to the online C API docs.

**Comment by evmar** [comment]
I pushed https://github.com/martine/gocairo/commit/232ddf78f05b5f79f78c384f215907e07f4063ee which improves the header fiddling -- no more hardcoded `/usr/include` and it will detect that you don't have xlib.  Unfortunately you have to check out the repo and build with `make` to have that work.  I'll take a look at the devhelp thing next.

**Comment by evmar** [comment]
https://github.com/martine/gocairo/commit/78183bc18da92a2077ed3f65f4acba41aadaca5d should fix the devhelp thing.  The generated godocs will not have links to the Cairo API docs for each function, though.

Feel free to reopen if I missed anything!

**Comment by tonydaly** [comment]
Heya, I'm trying to get this running on my machine and still getting a similar error to above:

```
$ make
go install github.com/martine/gocairo/cairo
# github.com/martine/gocairo/cairo
could not determine kind of name for C.CAIRO_STATUS_JBIG2_GLOBAL_MISSING
could not determine kind of name for C.cairo_surface_get_device_scale
could not determine kind of name for C.cairo_surface_set_device_scale
```

I've install cairo via homebrew. Any help appreciated.

**Comment by evmar** [comment]
What version of Cairo?  (See cairo-version.h)  I suspect homebrew gave you a version older than the current one.

You might try downloading this repo and running "make", which reruns the binding generation process.  Because generate the bindings code, if your cairo has a different API than the one the repo was built with, it will automatically pick up the differences.  If you do try that, could you show me the output of "git diff" after that? It will tell me what the needed difference is and perhaps give me a pointer to how to work around it.
